# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f9b1e98f5496f4ff8b6284f81f519d79431b14b298cf620070a1265ab72638501384dfe2bf958aa8d6e23b5b5d81ddbf74c7aff9c58a662de56c2d20264cf8

test:
  secret_key_base: 5c17b3abee4b2bfd7d10c4a2e16fedf6bd4ff73f79d8ffe41f1d646f866f881842720706ea13e9c05eb36804f10427b60b82d8709d5406fefaea006e61e825ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
